server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  main:
    web-application-type: reactive
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/GestionCreditosBancarios
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    urls:
      - name: clientes
        url: /servicioclientes/v3/api-docs
      - name: prestamos
        url: /servicioprestamos/v3/api-docs
      - name: transacciones
        url: /serviciotransacciones/v3/api-docs
      - name: cuentas
        url: /serviciocuentas/v3/api-docs
        
management:
  endpoints:
    web:
      exposure:
        include: "*"